config/routes.rb
Tryzee::Application.routes.draw do
  resources :results
  resources :searches
  resources :registers
  resources :users

  resources :searches

  get '/registers/new' => 'registers#new', as: 'new_register'
  post '/registers' => 'registers#create', as: 'registers'
  delete '/registers' => 'registers#destroy'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  match '/signout' => 'sessions#destroy', via: :delete

  root :to => 'pages#home'

  match '/how_it_works', to: 'pages#how_it_works'
  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/start', to: 'pages#start'
  match '/home', to: 'pages#home'
  match '/signin', to: 'pages#signin'
  match '/welcome', to: 'pages#welcome'
  match '/search', to: 'pages#search'

  get '/tryals/new', controller: 'tryals', action: 'new', as: 'new_tryal'
  post '/tryals', controller: 'tryals', action: 'create'

  get '/tryals', controller: 'tryals', action: 'index', as: 'tryals'
  get '/tryals/:id', controller: 'tryals', action: 'show', as: 'tryal'

  get '/tryals/:id/edit', controller: 'tryals', action: 'edit', as: 'edit_tryal'
  put '/tryals/:id', controller: 'tryals', action: 'update'

  delete '/tryals/:id', controller: 'tryals', action: 'destroy'

  get '/products/new', controller: 'products', action: 'new', as: 'new_product'
  post '/products', controller: 'products', action: 'create'

  get '/products', controller: 'products', action: 'index', as: 'products'
  get '/products/:id', controller: 'products', action: 'show', as: 'product'

  get '/products/:id/edit', controller: 'products', action: 'edit', as: 'edit_product'
  put '/products/:id', controller: 'products', action: 'update'

  delete '/products/:id', controller: 'products', action: 'destroy'

  get '/messages/new', controller: 'messages', action: 'new', as: 'new_message'
  post '/messages', controller: 'messages', action: 'create'

  get '/messages', controller: 'messages', action: 'index', as: 'messages'
  get '/messages/:id', controller: 'messages', action: 'show', as: 'message'

  get '/messages/:id/edit', controller: 'messages', action: 'edit', as: 'edit_message'
  put '/messages/:id', controller: 'messages', action: 'update'

  delete '/messages/:id', controller: 'messages', action: 'destroy'

  get '/models/new', controller: 'models', action: 'new', as: 'new_model'
  post '/models', controller: 'models', action: 'create'

  get '/models', controller: 'models', action: 'index', as: 'models'
  get '/models/:id', controller: 'models', action: 'show', as: 'model'

  get '/models/:id/edit', controller: 'models', action: 'edit', as: 'edit_model'
  put '/models/:id', controller: 'models', action: 'update'

  delete '/models/:id', controller: 'models', action: 'destroy'

  get '/manufacturers/new', controller: 'manufacturers', action: 'new', as: 'new_manufacturer'
  post '/manufacturers', controller: 'manufacturers', action: 'create'

  get '/manufacturers', controller: 'manufacturers', action: 'index', as: 'manufacturers'
  get '/manufacturers/:id', controller: 'manufacturers', action: 'show', as: 'manufacturer'

  get '/manufacturers/:id/edit', controller: 'manufacturers', action: 'edit', as: 'edit_manufacturer'
  put '/manufacturers/:id', controller: 'manufacturers', action: 'update'

  delete '/manufacturers/:id', controller: 'manufacturers', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create'

  get '/categories', controller: 'categories', action: 'index', as: 'categories'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  put '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

end

app/models/result.rb
class Result < ActiveRecord::Base
  attr_accessible :category_id, :location, :manufacturer_id, :model_id, :search_id, :user_id
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.json
  def index
    @results = Result.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @results }
    end
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @result = Result.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/new
  # GET /results/new.json
  def new
    @result = Result.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @result }
    end
  end

  # GET /results/1/edit
  def edit
    @result = Result.find(params[:id])
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(params[:result])

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render json: @result, status: :created, location: @result }
      else
        format.html { render action: "new" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /results/1
  # PUT /results/1.json
  def update
    @result = Result.find(params[:id])

    respond_to do |format|
      if @result.update_attributes(params[:result])
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to results_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :model_id %><br />
    <%= f.number_field :model_id %>
  </div>
  <div class="field">
    <%= f.label :manufacturer_id %><br />
    <%= f.number_field :manufacturer_id %>
  </div>
  <div class="field">
    <%= f.label :search_id %><br />
    <%= f.number_field :search_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h1>Listing results</h1>

<table>
  <tr>
    <th>User</th>
    <th>Location</th>
    <th>Model</th>
    <th>Manufacturer</th>
    <th>Search</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @results.each do |result| %>
  <tr>
    <td><%= result.user_id %></td>
    <td><%= result.location %></td>
    <td><%= result.model_id %></td>
    <td><%= result.manufacturer_id %></td>
    <td><%= result.search_id %></td>
    <td><%= result.category_id %></td>
    <td><%= link_to 'Show', result %></td>
    <td><%= link_to 'Edit', edit_result_path(result) %></td>
    <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @result.user_id %>
</p>

<p>
  <b>Location:</b>
  <%= @result.location %>
</p>

<p>
  <b>Model:</b>
  <%= @result.model_id %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @result.manufacturer_id %>
</p>

<p>
  <b>Search:</b>
  <%= @result.search_id %>
</p>

<p>
  <b>Category:</b>
  <%= @result.category_id %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>