config/routes.rb
Tryzee::Application.routes.draw do
  resources :results
  resources :searches
  resources :registers
  resources :users

  resources :searches

  get '/registers/new' => 'registers#new', as: 'new_register'
  post '/registers' => 'registers#create', as: 'registers'
  delete '/registers' => 'registers#destroy'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  match '/signout' => 'sessions#destroy', via: :delete

  root :to => 'pages#home'

  match '/how_it_works', to: 'pages#how_it_works'
  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/start', to: 'pages#start'
  match '/home', to: 'pages#home'
  match '/signin', to: 'pages#signin'
  match '/welcome', to: 'pages#welcome'
  match '/search', to: 'pages#search'

  get '/tryals/new', controller: 'tryals', action: 'new', as: 'new_tryal'
  post '/tryals', controller: 'tryals', action: 'create'

  get '/tryals', controller: 'tryals', action: 'index', as: 'tryals'
  get '/tryals/:id', controller: 'tryals', action: 'show', as: 'tryal'

  get '/tryals/:id/edit', controller: 'tryals', action: 'edit', as: 'edit_tryal'
  put '/tryals/:id', controller: 'tryals', action: 'update'

  delete '/tryals/:id', controller: 'tryals', action: 'destroy'

  get '/products/new', controller: 'products', action: 'new', as: 'new_product'
  post '/products', controller: 'products', action: 'create'

  get '/products', controller: 'products', action: 'index', as: 'products'
  get '/products/:id', controller: 'products', action: 'show', as: 'product'

  get '/products/:id/edit', controller: 'products', action: 'edit', as: 'edit_product'
  put '/products/:id', controller: 'products', action: 'update'

  delete '/products/:id', controller: 'products', action: 'destroy'

  get '/messages/new', controller: 'messages', action: 'new', as: 'new_message'
  post '/messages', controller: 'messages', action: 'create'

  get '/messages', controller: 'messages', action: 'index', as: 'messages'
  get '/messages/:id', controller: 'messages', action: 'show', as: 'message'

  get '/messages/:id/edit', controller: 'messages', action: 'edit', as: 'edit_message'
  put '/messages/:id', controller: 'messages', action: 'update'

  delete '/messages/:id', controller: 'messages', action: 'destroy'

  get '/models/new', controller: 'models', action: 'new', as: 'new_model'
  post '/models', controller: 'models', action: 'create'

  get '/models', controller: 'models', action: 'index', as: 'models'
  get '/models/:id', controller: 'models', action: 'show', as: 'model'

  get '/models/:id/edit', controller: 'models', action: 'edit', as: 'edit_model'
  put '/models/:id', controller: 'models', action: 'update'

  delete '/models/:id', controller: 'models', action: 'destroy'

  get '/manufacturers/new', controller: 'manufacturers', action: 'new', as: 'new_manufacturer'
  post '/manufacturers', controller: 'manufacturers', action: 'create'

  get '/manufacturers', controller: 'manufacturers', action: 'index', as: 'manufacturers'
  get '/manufacturers/:id', controller: 'manufacturers', action: 'show', as: 'manufacturer'

  get '/manufacturers/:id/edit', controller: 'manufacturers', action: 'edit', as: 'edit_manufacturer'
  put '/manufacturers/:id', controller: 'manufacturers', action: 'update'

  delete '/manufacturers/:id', controller: 'manufacturers', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create'

  get '/categories', controller: 'categories', action: 'index', as: 'categories'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  put '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  belongs_to :product

 end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by_id(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new
    @category.name = params[:name]
    
    if @category.save
            redirect_to categories_url
          else
      render 'new'
    end
  end

  def edit
    @category = Category.find_by_id(params[:id])
  end

  def update
    @category = Category.find_by_id(params[:id])
    @category.name = params[:name]
    
    if @category.save
            redirect_to categories_url
          else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find_by_id(params[:id])
    @category.destroy
        redirect_to categories_url
      end
end

app/views/categories/edit.html.erb
<h1>Editing Category #<%= @category.id %></h1>


<%= form_tag(category_url(@category), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @category.name %>
  </div>

  
  <div>
    <%= submit_tag "Update Category" %>
  </div>

<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<p><%= link_to 'Add a New Category', new_category_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
  
      <td><%= link_to 'Show', category_url(category) %></td>
      <td><%= link_to 'Edit', edit_category_url(category) %></td>
      <td><%= link_to 'Destroy', category_url(category), method: 'delete', data: { confirm: "Do you really want to delete this category?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>


<%= form_tag(categories_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

  
  <div>
    <%= submit_tag "Create Category" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1>Category #<%= @category.id %></h1>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>