config/routes.rb
Tryzee::Application.routes.draw do
  resources :results
  resources :searches
  resources :registers
  resources :users

  resources :searches

  get '/registers/new' => 'registers#new', as: 'new_register'
  post '/registers' => 'registers#create', as: 'registers'
  delete '/registers' => 'registers#destroy'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  match '/signout' => 'sessions#destroy', via: :delete

  root :to => 'pages#home'

  match '/how_it_works', to: 'pages#how_it_works'
  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/start', to: 'pages#start'
  match '/home', to: 'pages#home'
  match '/signin', to: 'pages#signin'
  match '/welcome', to: 'pages#welcome'
  match '/search', to: 'pages#search'

  get '/tryals/new', controller: 'tryals', action: 'new', as: 'new_tryal'
  post '/tryals', controller: 'tryals', action: 'create'

  get '/tryals', controller: 'tryals', action: 'index', as: 'tryals'
  get '/tryals/:id', controller: 'tryals', action: 'show', as: 'tryal'

  get '/tryals/:id/edit', controller: 'tryals', action: 'edit', as: 'edit_tryal'
  put '/tryals/:id', controller: 'tryals', action: 'update'

  delete '/tryals/:id', controller: 'tryals', action: 'destroy'

  get '/products/new', controller: 'products', action: 'new', as: 'new_product'
  post '/products', controller: 'products', action: 'create'

  get '/products', controller: 'products', action: 'index', as: 'products'
  get '/products/:id', controller: 'products', action: 'show', as: 'product'

  get '/products/:id/edit', controller: 'products', action: 'edit', as: 'edit_product'
  put '/products/:id', controller: 'products', action: 'update'

  delete '/products/:id', controller: 'products', action: 'destroy'

  get '/messages/new', controller: 'messages', action: 'new', as: 'new_message'
  post '/messages', controller: 'messages', action: 'create'

  get '/messages', controller: 'messages', action: 'index', as: 'messages'
  get '/messages/:id', controller: 'messages', action: 'show', as: 'message'

  get '/messages/:id/edit', controller: 'messages', action: 'edit', as: 'edit_message'
  put '/messages/:id', controller: 'messages', action: 'update'

  delete '/messages/:id', controller: 'messages', action: 'destroy'

  get '/models/new', controller: 'models', action: 'new', as: 'new_model'
  post '/models', controller: 'models', action: 'create'

  get '/models', controller: 'models', action: 'index', as: 'models'
  get '/models/:id', controller: 'models', action: 'show', as: 'model'

  get '/models/:id/edit', controller: 'models', action: 'edit', as: 'edit_model'
  put '/models/:id', controller: 'models', action: 'update'

  delete '/models/:id', controller: 'models', action: 'destroy'

  get '/manufacturers/new', controller: 'manufacturers', action: 'new', as: 'new_manufacturer'
  post '/manufacturers', controller: 'manufacturers', action: 'create'

  get '/manufacturers', controller: 'manufacturers', action: 'index', as: 'manufacturers'
  get '/manufacturers/:id', controller: 'manufacturers', action: 'show', as: 'manufacturer'

  get '/manufacturers/:id/edit', controller: 'manufacturers', action: 'edit', as: 'edit_manufacturer'
  put '/manufacturers/:id', controller: 'manufacturers', action: 'update'

  delete '/manufacturers/:id', controller: 'manufacturers', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create'

  get '/categories', controller: 'categories', action: 'index', as: 'categories'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  put '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :model_id, :photo_url, :category_name, :description, :manufacturer_name, :model_name, :category_id, :manufacturer_id

  belongs_to :model
  belongs_to :category
  belongs_to :user
  belongs_to :tryal
  has_many :messages
  belongs_to :search
  belongs_to :manufacturer

  def self.search(search)
    if search
      find(:all, :conditions => ['model_name LIKE ?', "%#{search}%"])
    elsif
      find(:all, :conditions => ['category_name LIKE ?',"%#{search}%"])

    elsif
      find(:all, :conditions => ['manufacturer_name LIKE ?',"%#{search}%"])

    else
      find(:all)
  end
end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @search = params[:search]
    @products = Product.search(@search)
  end


  def show
    @product = Product.find_by_id(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new
    @product.model_id = params[:model_id]
    @product.photo_url = params[:photo_url]
    @product.description = params[:description]
    @product.category_id = params[:category_id]

    if @product.save
            redirect_to products_url
          else
      render 'new'
    end
  end

  def edit
    @product = Product.find_by_id(params[:id])
  end

  def update
    @product = Product.find_by_id(params[:id])
    @product.model_id = params[:model_id]
    @product.photo_url = params[:photo_url]
    @product.description = params[:description]
    @product.category_id = params[:category_id]

    if @product.save
            redirect_to products_url
          else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find_by_id(params[:id])
    @product.destroy
        redirect_to products_url
      end
end

app/views/products/_product.html.erb
<div class="product">
  <h2><%= link_to product.description, product %></h2>
  <div class="details">

    <% if product.category %>
      | Category: <%= product.category.name %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product #<%= @product.id %></h1>


<%= form_tag(product_url(@product), method: 'put') do %>

  <div>
    <%= label_tag :model_id %><br />
    <%= number_field_tag :model_id, @product.model_id %>
  </div>

  <div>
    <%= label_tag :photo_url %><br />
    <%= text_field_tag :photo_url, @product.photo_url %>
  </div>

  <div>
    <%= label_tag :description %><br />
    <%= text_area_tag :description, @product.description %>
  </div>

  <div>
    <%= label_tag :category_id %><br />
    <%= number_field_tag :category_id, @product.category_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Product" %>
  </div>

<% end %>

app/views/products/index.html.erb
<h1>Search Results:</h1>

<div id="products">
  <%= render @products %>
</div>

<p><%= link_to "Advanced Search", new_search_path %>

app/views/products/new.html.erb
<h1>Add a New Product</h1>


<%= form_tag(products_url, method: 'post') do %>


  <div>
    <%= label_tag :model_id %><br />
    <%= number_field_tag :model_id %>
  </div>

    <div>
    <%= label_tag :photo_url %><br />
    <%= text_field_tag :photo_url %>
  </div>

    <div>
    <%= label_tag :description %><br />
    <%= text_area_tag :description %>
  </div>

    <div>
    <%= label_tag :lenders_description %><br />
    <%= text_area_tag :lenders_description  %>
   </div>

    <div>
    <%= label_tag :category_id %><br />
    <%= number_field_tag :category_id %>
  </div>


  <div>
    <%= submit_tag "Create Product" %>
  </div>
<% end %>

app/views/products/search.html.erb
<h1>Search products to Try</h1>

app/views/products/show.html.erb
<h1>Tryzee Item: <%= @product.model_name %></h1>

<p>
  <b>Model Name:</b>
  <%= @product.model_name %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @product.manufacturer_name %>
</p>

<p>
  <b>Model Number:</b>
  <%= @product.model_id %>
</p>

<p>
  <b>Photo url:</b>
  <%= @product.photo_url %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category_name %>
</p>

<%= link_to "Like what you see? Time to Tryzee!", new_tryal_url %>