config/routes.rb
Tryzee::Application.routes.draw do
  resources :results
  resources :searches
  resources :registers
  resources :users

  resources :searches

  get '/registers/new' => 'registers#new', as: 'new_register'
  post '/registers' => 'registers#create', as: 'registers'
  delete '/registers' => 'registers#destroy'

  get '/sessions/new' => 'sessions#new', as: 'new_session'
  post '/sessions' => 'sessions#create', as: 'sessions'
  match '/signout' => 'sessions#destroy', via: :delete

  root :to => 'pages#home'

  match '/how_it_works', to: 'pages#how_it_works'
  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/start', to: 'pages#start'
  match '/home', to: 'pages#home'
  match '/signin', to: 'pages#signin'
  match '/welcome', to: 'pages#welcome'
  match '/search', to: 'pages#search'

  get '/tryals/new', controller: 'tryals', action: 'new', as: 'new_tryal'
  post '/tryals', controller: 'tryals', action: 'create'

  get '/tryals', controller: 'tryals', action: 'index', as: 'tryals'
  get '/tryals/:id', controller: 'tryals', action: 'show', as: 'tryal'

  get '/tryals/:id/edit', controller: 'tryals', action: 'edit', as: 'edit_tryal'
  put '/tryals/:id', controller: 'tryals', action: 'update'

  delete '/tryals/:id', controller: 'tryals', action: 'destroy'

  get '/products/new', controller: 'products', action: 'new', as: 'new_product'
  post '/products', controller: 'products', action: 'create'

  get '/products', controller: 'products', action: 'index', as: 'products'
  get '/products/:id', controller: 'products', action: 'show', as: 'product'

  get '/products/:id/edit', controller: 'products', action: 'edit', as: 'edit_product'
  put '/products/:id', controller: 'products', action: 'update'

  delete '/products/:id', controller: 'products', action: 'destroy'

  get '/messages/new', controller: 'messages', action: 'new', as: 'new_message'
  post '/messages', controller: 'messages', action: 'create'

  get '/messages', controller: 'messages', action: 'index', as: 'messages'
  get '/messages/:id', controller: 'messages', action: 'show', as: 'message'

  get '/messages/:id/edit', controller: 'messages', action: 'edit', as: 'edit_message'
  put '/messages/:id', controller: 'messages', action: 'update'

  delete '/messages/:id', controller: 'messages', action: 'destroy'

  get '/models/new', controller: 'models', action: 'new', as: 'new_model'
  post '/models', controller: 'models', action: 'create'

  get '/models', controller: 'models', action: 'index', as: 'models'
  get '/models/:id', controller: 'models', action: 'show', as: 'model'

  get '/models/:id/edit', controller: 'models', action: 'edit', as: 'edit_model'
  put '/models/:id', controller: 'models', action: 'update'

  delete '/models/:id', controller: 'models', action: 'destroy'

  get '/manufacturers/new', controller: 'manufacturers', action: 'new', as: 'new_manufacturer'
  post '/manufacturers', controller: 'manufacturers', action: 'create'

  get '/manufacturers', controller: 'manufacturers', action: 'index', as: 'manufacturers'
  get '/manufacturers/:id', controller: 'manufacturers', action: 'show', as: 'manufacturer'

  get '/manufacturers/:id/edit', controller: 'manufacturers', action: 'edit', as: 'edit_manufacturer'
  put '/manufacturers/:id', controller: 'manufacturers', action: 'update'

  delete '/manufacturers/:id', controller: 'manufacturers', action: 'destroy'

  get '/categories/new', controller: 'categories', action: 'new', as: 'new_category'
  post '/categories', controller: 'categories', action: 'create'

  get '/categories', controller: 'categories', action: 'index', as: 'categories'
  get '/categories/:id', controller: 'categories', action: 'show', as: 'category'

  get '/categories/:id/edit', controller: 'categories', action: 'edit', as: 'edit_category'
  put '/categories/:id', controller: 'categories', action: 'update'

  delete '/categories/:id', controller: 'categories', action: 'destroy'

end

app/views/layouts/_footer.html.erb
<footer>
<p>THIS IS THE FOOTER</p>
</footer>

app/views/layouts/_header.html.erb
<div id="login_top">
	<% if signed_in? %>
  		<%= link_to "Dashboard", welcome_path %>
  		<%= link_to "Sign Out",  signout_path, method: "delete" %>
  	<% else %>
		<%= form_for(:session, url: sessions_path) do |f| %>
  		<%= f.text_field :email, :size => 25, :placeholder => "Email" %>
  		<%= f.password_field :password, :size => 15, :placeholder => "Password" %>
  		<%= f.submit "Sign In" %>
		<% end %>
		<div class="or_sign_up">
		<p> or <%= link_to "sign up!", new_user_path %>
		</div>
	<% end %>
</div>

<header>

<%= image_tag("tryzeelogo.png", :height => "100", :alt => "Tryzee") %>

<nav>
<ul>
<li><%= link_to "Home", root_url %></li>
<li><%= link_to "How it Works", how_it_works_url %></li>
<li><%= link_to "Help", help_url %></li>
<li><%= link_to "About", about_url %></li>
<% if signed_in? %>
  <li>%= link_to "Dashboard", about_url %></li>
  <li><%= link_to "Sign Out", welcome_path, method: "delete" %></li>
  <% else %>
  <li><%= link_to "Sign In", new_session_url%></li>
<% end %>
</ul>
</nav>


</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tryzee</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,700,900' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>



<article>

		<p id="notice"><%= notice %></p>
		<%= yield %>

</article>



	<%= render 'layouts/footer' %>


<%= session.inspect if Rails.env.development? %>
<br>
<br>
<%= debug(params) if Rails.env.development? %><br>
<br>


</body>
</html>